version: "3.8"

services:
  app:
    build: .
    container_name: question-server
    restart: on-failure
    volumes:
      - ./src/main/resources/libs:/app/src/main/resources/libs
    ports:
      - "8081:8081"
    env_file:
      - .env